main:main.cpp
	arm-linux-g++  -std=c++11   main.cpp cJSON.c  -o main   -I /home/gec/libcurl/include/   -I  /home/gec/libjson/include/  -I /home/gec/libopenssl/include/  -L /home/gec/libcurl/lib   -L  /home/gec/libjson   -L /home/gec/libopenssl/lib  -lcurl -lcrypto  -ljsoncpp  -lssl  -lpthread
clean:
	rm main